-- DROP TABLE IF EXISTS meetingroom;
CREATE TABLE IF NOT EXISTS meetingroom (
  id BIGSERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  date VARCHAR(60) NOT NULL,
  startHour VARCHAR(5) NOT NULL,
  endHour VARCHAR(5) NOT NULL
);